spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/license
    username: license
    password: license
    
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        register-health-indicator: true
    instances:
      licenseService:
        base-config: default
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
        